# Generated by Django 4.2.1 on 2023-05-04 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bgpviewer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='local_timezone',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
