# Generated by Django 4.2.1 on 2023-05-18 08:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bgpviewer', '0002_record_local_timezone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='create_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
