# Generated by Django 4.2.1 on 2023-05-18 08:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bgpviewer', '0005_alter_record_create_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='create_at',
            field=models.DateField(default=datetime.datetime(2023, 5, 18, 8, 43, 17, 763225, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
