# Generated by Django 4.2.1 on 2023-05-18 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bgpviewer', '0012_alter_record_create_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prefix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix_le', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('prefix_le', models.ManyToManyField(through='bgpviewer.Record', to='bgpviewer.prefix')),
            ],
        ),
        migrations.AlterField(
            model_name='record',
            name='prefix',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bgpviewer.prefix'),
        ),
        migrations.AlterField(
            model_name='record',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bgpviewer.site'),
        ),
    ]
