# Generated by Django 4.2.1 on 2023-05-18 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bgpviewer', '0013_prefix_site_alter_record_prefix_alter_record_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='prefix',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='record',
            name='site',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='Relist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bgpviewer.prefix')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bgpviewer.site')),
            ],
        ),
        migrations.AlterField(
            model_name='site',
            name='prefix_le',
            field=models.ManyToManyField(through='bgpviewer.Relist', to='bgpviewer.prefix'),
        ),
    ]
